#!/usr/bin/env node
// Copies Kutip/.env (root) subset into Kutip/web/.env.local for Next.js.
// Keeps only keys that web/ actually reads — avoids leaking forge-only secrets
// (e.g. OPERATOR_BPS which the contract deploy script needs but the web app doesn't).

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const rootEnv = resolve(root, ".env");
const webEnvLocal = resolve(root, "web/.env.local");

if (!existsSync(rootEnv)) {
  console.error("[sync-env] Kutip/.env not found. Copy .env.example first.");
  process.exit(1);
}

const WEB_KEYS = new Set([
  "KITE_RPC_URL",
  "NEXT_PUBLIC_KITE_EXPLORER",
  "NEXT_PUBLIC_SITE_URL",
  "PRIVATE_KEY",
  "SERVICE_PRIVATE_KEY",
  "NEXT_PUBLIC_ATTRIBUTION_LEDGER",
  "NEXT_PUBLIC_ESCROW_ADDRESS",
  "NEXT_PUBLIC_BOUNTY_MARKET_ADDRESS",
  "NEXT_PUBLIC_AGENT_REPUTATION_ADDRESS",
  "NEXT_PUBLIC_AGENT_REGISTRY_ADDRESS",
  "NEXT_PUBLIC_ERC6551_REGISTRY",
  "NEXT_PUBLIC_ERC6551_ACCOUNT_IMPL",
  "NEXT_PUBLIC_AGENT_OPERATOR_ADDRESS",
  "NEXT_PUBLIC_ECOSYSTEM_FUND_ADDRESS",
  "NEXT_PUBLIC_ECOSYSTEM_SAFE_PENDING",
  "OPENROUTER_API_KEY",
  "OPENROUTER_MODEL",
  "OPENROUTER_FALLBACK_MODEL",
  "ANTHROPIC_API_KEY",
  "ANTHROPIC_MODEL",
  "KUTIP_DEMO_MODE",
  "KUTIP_USE_AA",
  "KUTIP_ROUTE_UNCLAIMED_TO_ESCROW",
  "KUTIP_USE_SEMANTIC_SCHOLAR",
  "ATTRIBUTION_LEDGER_DEPLOY_BLOCK",
  "NEXT_PUBLIC_SUBGRAPH_URL",
  "KUTIP_MIRROR_ADDRESS",
  "KUTIP_MIRROR_RPC_URL",
  "KUTIP_MIRROR_CHAIN_ID",
  "NEXT_PUBLIC_NAME_REGISTRY",
  "NEXT_PUBLIC_OPERATOR_SAFE",
  "NEXT_PUBLIC_YIELD_VAULT",
  "KUTIP_SAFE_THRESHOLD",
  "KUTIP_SAFE_OWNERS",
  "ORCID_CLIENT_ID",
  "ORCID_CLIENT_SECRET",
  "ORCID_COOKIE_SECRET",
  "ORCID_OAUTH_BASE"
]);

const lines = readFileSync(rootEnv, "utf-8").split(/\r?\n/);
const out = [
  "# Auto-generated by scripts/sync-env.mjs — edit Kutip/.env, then re-run.",
  ""
];

for (const line of lines) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#")) continue;
  const eq = trimmed.indexOf("=");
  if (eq === -1) continue;
  const key = trimmed.slice(0, eq).trim();
  if (WEB_KEYS.has(key)) out.push(trimmed);
}

writeFileSync(webEnvLocal, out.join("\n") + "\n");
console.log(`[sync-env] Wrote ${out.length - 2} vars → web/.env.local`);
